// premium-content.js
// Content script del modo "Formulario Premium". Se inyecta en el mismo
// contexto de página que content.js (declarado junto a él en
// manifest.json) pero es un módulo totalmente independiente: no comparte
// variables ni funciones con content.js (duplica un par de helpers chicos
// a propósito, para no arriesgar tocar el código de Auto Action).
//
// Responsabilidades:
//  1) Modo "registrar campo": resalta el elemento bajo el mouse y captura
//     el que se clickee, generando selectores robustos para encontrarlo de
//     nuevo más adelante (nunca se guarda una referencia DOM).
//  2) Motor de ejecución: dado un formulario (lista de campos + acciones),
//     localiza cada elemento (con espera/reintento si todavía no existe en
//     el DOM) y ejecuta su acción, disparando los eventos necesarios para
//     que React/Vue/Angular detecten el cambio.

(() => {
  if (window.__autoActionPremiumContentLoaded) return;
  window.__autoActionPremiumContentLoaded = true;

  class FieldActionError extends Error {
    constructor(code, message) {
      super(message);
      this.code = code;
    }
  }

  function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  // ---------------------------------------------------------------------
  // Selectores robustos
  // ---------------------------------------------------------------------

  function cssEscape(value) {
    if (window.CSS && CSS.escape) return CSS.escape(value);
    return String(value).replace(/[^a-zA-Z0-9_-]/g, "\\$&");
  }

  function attrSelector(tag, attr, value) {
    return `${tag}[${attr}="${value.replace(/"/g, '\\"')}"]`;
  }

  function isUniqueMatch(selector, el) {
    try {
      const matches = document.querySelectorAll(selector);
      return matches.length === 1 && matches[0] === el;
    } catch (e) {
      return false;
    }
  }

  // Heurística liviana para no priorizar ids que claramente son generados
  // al vuelo por un framework (ember123, ":r3:", uuids, radix-:r1:, etc.).
  // Si un id "parece raro" igual se guarda, solo baja de prioridad.
  function looksAutogenerated(id) {
    if (/^:.+:$/.test(id)) return true;
    if (/^(ember|radix|react|mui|mat)[-:]?\d/i.test(id)) return true;
    if (/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}/i.test(id)) return true;
    const digits = id.replace(/[^0-9]/g, "").length;
    return digits >= 4 && digits > id.length * 0.35;
  }

  function buildCssPath(el) {
    if (el.id && isUniqueMatch(`#${cssEscape(el.id)}`, el)) return `#${cssEscape(el.id)}`;

    const parts = [];
    let node = el;
    while (node && node.nodeType === 1 && node !== document.documentElement) {
      let part = node.tagName.toLowerCase();
      if (node.id) {
        parts.unshift(`${part}#${cssEscape(node.id)}`);
        break; // un ancestro con id alcanza para anclar el camino
      }
      const parent = node.parentElement;
      if (parent) {
        const siblings = Array.from(parent.children).filter((c) => c.tagName === node.tagName);
        if (siblings.length > 1) {
          part += `:nth-of-type(${siblings.indexOf(node) + 1})`;
        }
      }
      parts.unshift(part);
      const candidate = parts.join(" > ");
      if (isUniqueMatch(candidate, el)) return candidate;
      node = node.parentElement;
    }
    return parts.join(" > ");
  }

  function buildXPath(el) {
    if (el.id) return `//*[@id="${el.id}"]`;
    const parts = [];
    let node = el;
    while (node && node.nodeType === 1) {
      let index = 1;
      let sibling = node.previousElementSibling;
      while (sibling) {
        if (sibling.tagName === node.tagName) index++;
        sibling = sibling.previousElementSibling;
      }
      parts.unshift(`${node.tagName.toLowerCase()}[${index}]`);
      node = node.parentElement;
    }
    return "/" + parts.join("/");
  }

  function generateSelectors(el) {
    const tag = el.tagName.toLowerCase();
    const candidates = [];

    for (const attr of ["data-testid", "data-test", "data-qa", "data-cy", "data-automation-id"]) {
      const value = el.getAttribute(attr);
      if (value) {
        const sel = attrSelector(tag, attr, value);
        if (isUniqueMatch(sel, el)) candidates.push({ type: attr, value: sel });
      }
    }

    if (el.id && !looksAutogenerated(el.id)) {
      const sel = `#${cssEscape(el.id)}`;
      if (isUniqueMatch(sel, el)) candidates.push({ type: "id", value: sel });
    }

    const name = el.getAttribute("name");
    if (name) {
      const sel = attrSelector(tag, "name", name);
      if (isUniqueMatch(sel, el)) candidates.push({ type: "name", value: sel });
    }

    const ariaLabel = el.getAttribute("aria-label");
    if (ariaLabel) {
      const sel = attrSelector(tag, "aria-label", ariaLabel);
      if (isUniqueMatch(sel, el)) candidates.push({ type: "aria-label", value: sel });
    }

    const placeholder = el.getAttribute("placeholder");
    if (placeholder) {
      const sel = attrSelector(tag, "placeholder", placeholder);
      if (isUniqueMatch(sel, el)) candidates.push({ type: "placeholder", value: sel });
    }

    if (el.id && looksAutogenerated(el.id)) {
      const sel = `#${cssEscape(el.id)}`;
      if (isUniqueMatch(sel, el)) candidates.push({ type: "id-weak", value: sel });
    }

    candidates.push({ type: "css-path", value: buildCssPath(el) });
    candidates.push({ type: "xpath", value: buildXPath(el) });

    return candidates;
  }

  function evalXPath(xpath) {
    try {
      return document.evaluate(xpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null)
        .singleNodeValue;
    } catch (e) {
      return null;
    }
  }

  function pickBestMatch(matches, meta) {
    let bestScore = -1;
    let best = null;
    for (const candidate of matches) {
      let score = 0;
      if (meta.tagName && candidate.tagName.toLowerCase() === meta.tagName) score += 1;
      if (meta.inputType && candidate.getAttribute("type") === meta.inputType) score += 1;
      if (meta.placeholder && candidate.getAttribute("placeholder") === meta.placeholder) score += 2;
      if (meta.nameAttr && candidate.getAttribute("name") === meta.nameAttr) score += 2;
      if (score > bestScore) {
        bestScore = score;
        best = candidate;
      }
    }
    return best;
  }

  function locateElement(field) {
    for (const sel of field.selectors || []) {
      if (sel.type === "xpath") {
        const el = evalXPath(sel.value);
        if (el) return el;
        continue;
      }
      try {
        const matches = document.querySelectorAll(sel.value);
        if (matches.length === 1) return matches[0];
        if (matches.length > 1) {
          const best = pickBestMatch(matches, field.meta || {});
          if (best) return best;
        }
      } catch (e) {
        continue;
      }
    }
    return null;
  }

  function waitForElement(field, timeoutMs) {
    return new Promise((resolve) => {
      const existing = locateElement(field);
      if (existing) {
        resolve(existing);
        return;
      }

      let settled = false;
      const timer = setTimeout(() => {
        if (settled) return;
        settled = true;
        observer.disconnect();
        resolve(null);
      }, timeoutMs);

      const observer = new MutationObserver(() => {
        if (settled) return;
        const found = locateElement(field);
        if (found) {
          settled = true;
          clearTimeout(timer);
          observer.disconnect();
          resolve(found);
        }
      });
      observer.observe(document.documentElement, { childList: true, subtree: true, attributes: true });
    });
  }

  // ---------------------------------------------------------------------
  // Detección de tipo de elemento / sugerencias
  // ---------------------------------------------------------------------

  function detectElementKind(el) {
    const tag = el.tagName.toLowerCase();
    if (tag === "select") return "select";
    if (tag === "textarea") return "textarea";
    if (el.isContentEditable) return "contenteditable";
    if (tag === "input") {
      const type = (el.getAttribute("type") || "text").toLowerCase();
      if (type === "checkbox") return "checkbox";
      if (type === "radio") return "radio";
      if (["button", "submit", "reset"].includes(type)) return "button";
      return "input";
    }
    if (tag === "button") return "button";
    if (tag === "a" && el.hasAttribute("href")) return "button";
    return "other";
  }

  function suggestAction(kind) {
    switch (kind) {
      case "select":
        return "selectOption";
      case "checkbox":
        return "toggle";
      case "radio":
      case "button":
        return "click";
      default:
        return "type";
    }
  }

  function suggestLabel(el) {
    if (el.id) {
      const byFor = document.querySelector(`label[for="${cssEscape(el.id)}"]`);
      if (byFor && byFor.textContent.trim()) return byFor.textContent.trim().replace(/\s+/g, " ").slice(0, 60);
    }
    const wrappingLabel = el.closest("label");
    if (wrappingLabel && wrappingLabel.textContent.trim()) {
      return wrappingLabel.textContent.trim().replace(/\s+/g, " ").slice(0, 60);
    }
    if (el.getAttribute("aria-label")) return el.getAttribute("aria-label");
    if (el.getAttribute("placeholder")) return el.getAttribute("placeholder");
    if (["button", "a"].includes(el.tagName.toLowerCase()) && el.textContent.trim()) {
      return el.textContent.trim().replace(/\s+/g, " ").slice(0, 60);
    }
    if (el.getAttribute("name")) return el.getAttribute("name");
    if (el.id) return el.id;
    return `Campo ${el.tagName.toLowerCase()}`;
  }

  function captureMeta(el) {
    return {
      tagName: el.tagName.toLowerCase(),
      inputType: el.tagName.toLowerCase() === "input" ? el.getAttribute("type") || "text" : null,
      nameAttr: el.getAttribute("name") || null,
      idAttr: el.id || null,
      placeholder: el.getAttribute("placeholder") || null,
      ariaLabel: el.getAttribute("aria-label") || null,
      textSnippet: (el.textContent || "").trim().slice(0, 80) || null,
    };
  }

  // ---------------------------------------------------------------------
  // Modo "registrar campo"
  // ---------------------------------------------------------------------

  let captureState = null;

  function startFieldCapture(formId, fieldId) {
    if (captureState) return;

    const host = document.createElement("div");
    host.id = "auto-action-premium-overlay-host";
    host.style.all = "initial";
    (document.body || document.documentElement).appendChild(host);
    const shadow = host.attachShadow({ mode: "closed" });

    const style = document.createElement("style");
    style.textContent = `
      .hint {
        position: fixed; top: 16px; left: 50%; transform: translateX(-50%);
        background: #16161f; color: #f1f1f5; font: 13px/1.4 -apple-system, system-ui, sans-serif;
        padding: 8px 14px; border-radius: 8px; border: 1px solid #2c2c3a;
        box-shadow: 0 4px 16px rgba(0,0,0,.4); z-index: 2147483647; pointer-events: none;
      }
      .highlight {
        position: fixed; pointer-events: none; z-index: 2147483646;
        border: 2px solid #3b82f6; background: rgba(59, 130, 246, 0.14);
        border-radius: 4px; display: none;
      }
      .highlight.captured {
        border-color: #22c55e; background: rgba(34, 197, 94, 0.18);
      }
    `;

    const hint = document.createElement("div");
    hint.className = "hint";
    hint.textContent = "Pasá el mouse sobre un campo y hacé click para registrarlo · Esc para cancelar";
    const highlight = document.createElement("div");
    highlight.className = "highlight";

    shadow.appendChild(style);
    shadow.appendChild(hint);
    shadow.appendChild(highlight);

    captureState = { formId, fieldId, host, highlight, hoverTarget: null };

    document.addEventListener("mousemove", onCaptureMouseMove, true);
    document.addEventListener("click", onCaptureClick, true);
    document.addEventListener("keydown", onCaptureKeyDown, true);
  }

  function onCaptureMouseMove(e) {
    if (!captureState) return;
    const target = e.target;
    if (!target || target === captureState.hoverTarget) return;
    captureState.hoverTarget = target;
    const rect = target.getBoundingClientRect();
    Object.assign(captureState.highlight.style, {
      display: "block",
      left: `${rect.left}px`,
      top: `${rect.top}px`,
      width: `${rect.width}px`,
      height: `${rect.height}px`,
    });
  }

  function onCaptureClick(e) {
    if (!captureState) return;
    e.preventDefault();
    e.stopPropagation();
    e.stopImmediatePropagation();

    const target = captureState.hoverTarget || e.target;
    const kind = detectElementKind(target);
    const capture = {
      elementKind: kind,
      suggestedAction: suggestAction(kind),
      suggestedLabel: suggestLabel(target),
      selectors: generateSelectors(target),
      meta: captureMeta(target),
    };

    captureState.highlight.classList.add("captured");

    chrome.runtime.sendMessage({
      type: "PREMIUM_FIELD_CAPTURED",
      formId: captureState.formId,
      fieldId: captureState.fieldId,
      capture,
    });

    setTimeout(cleanupCapture, 400);
  }

  function onCaptureKeyDown(e) {
    if (!captureState) return;
    if (e.key === "Escape") {
      e.preventDefault();
      e.stopPropagation();
      chrome.runtime.sendMessage({ type: "PREMIUM_CAPTURE_CANCELLED" });
      cleanupCapture();
    }
  }

  function cleanupCapture() {
    if (!captureState) return;
    document.removeEventListener("mousemove", onCaptureMouseMove, true);
    document.removeEventListener("click", onCaptureClick, true);
    document.removeEventListener("keydown", onCaptureKeyDown, true);
    captureState.host.remove();
    captureState = null;
  }

  // ---------------------------------------------------------------------
  // Ejecución de acciones sobre un campo ya localizado
  // ---------------------------------------------------------------------

  // Truco necesario para que React/Vue/Angular detecten el cambio: estos
  // frameworks envuelven la propiedad "value" con su propio setter, así
  // que "el.value = x" no dispara su lógica interna. Llamando al setter
  // nativo del prototipo (el que el framework pisó) y disparando luego un
  // evento "input" real, el framework lo procesa como si el usuario
  // hubiera tipeado.
  function setNativeValue(el, value) {
    const proto = Object.getPrototypeOf(el);
    const desc = Object.getOwnPropertyDescriptor(proto, "value");
    if (desc && desc.set) {
      desc.set.call(el, value);
    } else {
      el.value = value;
    }
    el.dispatchEvent(new Event("input", { bubbles: true }));
    el.dispatchEvent(new Event("change", { bubbles: true }));
  }

  function dispatchMouseOn(el, type, buttons) {
    const rect = el.getBoundingClientRect();
    const clientX = rect.left + rect.width / 2;
    const clientY = rect.top + rect.height / 2;
    el.dispatchEvent(
      new MouseEvent(type, {
        bubbles: true,
        cancelable: true,
        composed: true,
        view: window,
        clientX,
        clientY,
        button: 0,
        buttons,
      })
    );
  }

  function dispatchKeyOn(el, spec) {
    try {
      el.focus({ preventScroll: true });
    } catch (e) {
      /* no enfocable, se ignora */
    }
    el.dispatchEvent(
      new KeyboardEvent("keydown", { bubbles: true, cancelable: true, composed: true, ...spec, which: spec.keyCode })
    );
    el.dispatchEvent(
      new KeyboardEvent("keyup", { bubbles: true, cancelable: true, composed: true, ...spec, which: spec.keyCode })
    );
  }

  function performHoldClick(el) {
    return new Promise((resolve) => {
      dispatchMouseOn(el, "mousedown", 1);
      setTimeout(() => {
        dispatchMouseOn(el, "mouseup", 0);
        dispatchMouseOn(el, "click", 0);
        resolve();
      }, 3000);
    });
  }

  async function performFieldAction(el, field) {
    try {
      el.scrollIntoView({ block: "center", inline: "nearest", behavior: "instant" });
    } catch (e) {
      /* elementos fuera de un contenedor con scroll normal pueden fallar acá, se ignora */
    }
    await sleep(60);

    if (el.disabled) {
      throw new FieldActionError("disabled", "El campo está deshabilitado.");
    }

    switch (field.action) {
      case "type": {
        const kind = detectElementKind(el);
        el.focus({ preventScroll: true });
        if (kind === "contenteditable") {
          document.execCommand("selectAll", false, null);
          const inserted = document.execCommand("insertText", false, field.value ?? "");
          if (!inserted) {
            el.textContent = field.value ?? "";
            el.dispatchEvent(new Event("input", { bubbles: true }));
          }
        } else {
          setNativeValue(el, field.value ?? "");
        }
        el.blur();
        break;
      }
      case "selectOption": {
        const options = Array.from(el.options || []);
        const wanted = field.value ?? "";
        const match =
          options.find((o) => o.value === wanted) ||
          options.find((o) => o.textContent.trim() === wanted) ||
          options.find((o) => o.textContent.trim().toLowerCase() === wanted.toLowerCase());
        if (!match) {
          throw new FieldActionError("option_not_found", `No se encontró la opción "${wanted}".`);
        }
        setNativeValue(el, match.value);
        break;
      }
      case "toggle": {
        const desired = field.value === "uncheck" ? false : field.value === "check" ? true : !el.checked;
        if (el.checked !== desired) el.click();
        break;
      }
      case "click":
        el.click();
        break;
      case "holdClick":
        await performHoldClick(el);
        break;
      case "space":
        dispatchKeyOn(el, { code: "Space", key: " ", location: 0, keyCode: 32 });
        break;
      case "enter":
        dispatchKeyOn(el, { code: "Enter", key: "Enter", location: 0, keyCode: 13 });
        break;
      case "numpadEnter":
        dispatchKeyOn(el, { code: "NumpadEnter", key: "Enter", location: 3, keyCode: 13 });
        break;
      default:
        throw new FieldActionError("unknown_action", `Acción desconocida: ${field.action}`);
    }
  }

  // ---------------------------------------------------------------------
  // Motor de ejecución del formulario completo
  // ---------------------------------------------------------------------

  let runState = null; // { stopRequested }

  function reportProgress(formId, patch) {
    chrome.runtime.sendMessage({ type: "PREMIUM_SET_RUNTIME", patch: { formId, ...patch } }).catch(() => {});
  }

  async function runForm(form) {
    if (runState) return; // ya hay una corrida en curso
    runState = { stopRequested: false };
    const total = form.fields.length;

    reportProgress(form.id, {
      status: "running",
      currentIndex: -1,
      totalFields: total,
      currentFieldLabel: null,
      currentAction: null,
      message: null,
      startedAt: Date.now(),
      finishedAt: null,
    });

    for (let i = 0; i < total; i++) {
      if (runState.stopRequested) {
        reportProgress(form.id, { status: "done", message: "Detenido manualmente.", finishedAt: Date.now() });
        runState = null;
        return;
      }

      const field = form.fields[i];
      reportProgress(form.id, {
        currentIndex: i,
        currentFieldLabel: field.label,
        currentAction: "esperando",
        message: null,
      });

      const el = await waitForElement(field, form.waitTimeoutMs || 5000);

      if (runState.stopRequested) {
        reportProgress(form.id, { status: "done", message: "Detenido manualmente.", finishedAt: Date.now() });
        runState = null;
        return;
      }

      if (!el) {
        reportProgress(form.id, { currentAction: "no-encontrado", message: `No se encontró: "${field.label}"` });
        if (form.stopOnMissing) {
          reportProgress(form.id, {
            status: "error",
            message: `Detenido: no se encontró "${field.label}".`,
            finishedAt: Date.now(),
          });
          runState = null;
          return;
        }
        continue;
      }

      reportProgress(form.id, { currentAction: "ejecutando" });
      try {
        await performFieldAction(el, field);
      } catch (err) {
        reportProgress(form.id, { currentAction: "error", message: `Error en "${field.label}": ${err.message}` });
        if (form.stopOnMissing) {
          reportProgress(form.id, { status: "error", message: `Detenido: ${err.message}`, finishedAt: Date.now() });
          runState = null;
          return;
        }
        continue;
      }

      if (i < total - 1 && form.delayMs > 0) await sleep(form.delayMs);
    }

    reportProgress(form.id, {
      status: "done",
      currentAction: null,
      message: "Formulario completado.",
      finishedAt: Date.now(),
    });

    if (form.reloadOnFinish) {
      reportProgress(form.id, { message: "Recargando página..." });
      await sleep(Math.max(0, form.reloadDelayMs || 0));
      location.reload();
      return;
    }

    runState = null;
  }

  // ---------------------------------------------------------------------
  // Mensajería
  // ---------------------------------------------------------------------

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (msg?.type === "PREMIUM_START_CAPTURE") {
      startFieldCapture(msg.formId, msg.fieldId || null);
      sendResponse({ ok: true });
      return;
    }
    if (msg?.type === "PREMIUM_RUN_FORM") {
      if (runState) {
        sendResponse({ ok: false, error: "already_running" });
        return;
      }
      runForm(msg.form);
      sendResponse({ ok: true });
      return;
    }
    if (msg?.type === "PREMIUM_STOP_RUN") {
      if (runState) runState.stopRequested = true;
      sendResponse({ ok: true });
      return;
    }
  });
})();
